### ISSUE TITLE
Runtime errors

### ISSUE THREAD

**Issue by JamesColl-NOAA** [NOAA-OWP/ras2fim#10]
@JamesColl-NOAA to debug

Run error encountered in Iowa data: 

## Current behaviors to correct:  
* DEM tile not downloaded (addressed in most recent version)
* e.g.( 07080107_USACE) - TypeError: iteration over a 0-d array
* e.g.( 07100003) - VRT not generated when it is expected

**Comment by BradfordBates-NOAA** [comment]
@JamesColl-NOAA Please split this into multiple issues to organize buck tracking

**Comment by BradfordBates-NOAA** [comment]
@JamesColl-NOAA Please finish creating the issues for these as we talked about on Monday and again on Friday. And please provide detailed descriptions of the errors so that Andy has time to understand before our meeting next week.

**Comment by BradfordBates-NOAA** [comment]
Closing this issue because individual issues were created for these.
