### ISSUE TITLE
[21pt] RRASSLER -- Preprocessing Original HEC-RAS Models

### ISSUE THREAD

**Issue by hhs732** [NOAA-OWP/ras2fim#109]

**Comment by BradfordBates-NOAA** [comment]
24pts is too many for one Sprint. Recommend tagging this as an "Epic" and creating sub-tasks

**Comment by RobHanna-NOAA** [comment]
No specific goals or tasks. We are considering closing this card.

**Comment by RobHanna-NOAA** [comment]
Not specific and is now split to other smaller cards.
