### ISSUE TITLE
[5pt] Standardize output location of depth grids, hec-ras output folders and rating curves

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#117]
A recent change created a mis-match of output locations from some files.
Depth grid files, folder 05 hec-ras output folders and rating curves now live in separate locations.

Pre recent change:  (example)

\05_hecras_output\HUC_120401010302\1466236\Depth_Grid\1466236-1.tif (and more tifs)
\05_hecras_output\HUC_120401010302\1466236\HEC-RAS\ (various files and folders)
\05_hecras_output\HUC_120401010302\1466236\Rating_Curve\1466236_rating_curve.csv

Post recent change:  (example)
\**06_metric\Depth_Grid**\HUC_120401010302\1466236\1466236-1.tif (and more tifs)
\05_hecras_output\HUC_120401010302\1466236\HEC-RAS\ (various files and folders)
\05_hecras_output\HUC_120401010302\1466236\Rating_Curve\1466236_rating_curve.csv

Consider standardizing the outputs, or possibly putting them back to their original locations.

**Comment by AliForghani-NOAA** [comment]
The new plan (similar to the original plan for standardization), as discussed in Scrum, is to be:
*06_metric\Depth_Grid*\HUC_120401010302\1466236\1466236-1.tif (and more tifs)
*06_metric\RatingCurve*\HUC_120401010302\1466236\Rating_Curve\1466236_rating_curve.csv
\05_hecras_output\HUC_120401010302\1466236\HEC-RAS\ (various files and folders)
\05_hecras_output\HUC_120401010302\1466236\Rating_Curve\1466236_rating_curve.cs
