### ISSUE TITLE
[8pt] Update catchments / maxments code to be driven by rating curves

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#118]
Not sure if we will need this, but currently calculating maxments is done by loading and manipulating file names. This would likely be quicker by loading rating curves and figuring out the maxmnet tif from that.

Maybe?  Check with Laura first to make sure there are not any accidental by products.

**Comment by RobHanna-NOAA** [comment]
On hold.. likely no longer required as we move to geocurves

**Comment by CarsonPruitt-NOAA** [comment]
Irrelevant now due to geocurves
