### ISSUE TITLE
[18pt] SRC Issue -- Nonmonotonic RC

### ISSUE THREAD

**Issue by hhs732** [NOAA-OWP/ras2fim#122]
Some hec-ras models creates nonmonotonic rating curves. 

![Image](https://github.com/NOAA-OWP/ras2fim/assets/23247850/a208c331-59db-4731-b9bc-3550165ea7e1)

**Comment by hhs732** [comment]
@CarsonPruitt-NOAA 
@LauraKeys-NOAA 
@JamesColl-NOAA

**Comment by LauraKeys-NOAA** [comment]
This issue is tied to the downstream boundary conditions and hopefully will be resolved in ras2fim v2. We will test the updated results for this issue to verify that everything looks good/improved.
