### ISSUE TITLE
[13pt] Empty Geometry - 12040101

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#130]
During a scale run of 12040101 a bunch of unique error messages in step 1 were recorded, suggesting bad models

Compute HEC-RAS Models: 42
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1467846_CRYSTAL CREEK TRIBUTARY NO 8_g10_1689344233\CRYSTAL CREEK TRIBUTARY NO 8.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1467950_Crystal Creek 046_g10_1689344233\Crystal Creek 046.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1467950_STEWARTS CREEK TRIBUTARY NO 1_g10_1689344233\STEWARTS CREEK TRIBUTARY NO 1.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1467974_NORTH FORK STEWARTS CREEK_g10_1689344233\NORTH FORK STEWARTS CREEK.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468024_Crystal Creek 024_g10_1689344233\Crystal Creek 024.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468024_CRYSTAL CREEK TRIBUTARY NO 3_g10_1689344233\CRYSTAL CREEK TRIBUTARY NO 3.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468024_CRYSTAL CREEK TRIBUTARY NO 4_g10_1689344233\CRYSTAL CREEK TRIBUTARY NO 4.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468024_CRYSTAL CREEK TRIBUTARY NO 6_g10_1689344233\CRYSTAL CREEK TRIBUTARY NO 6.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468024_CRYSTAL CREEK TRIBUTARY NO 7_g10_1689344233\CRYSTAL CREEK TRIBUTARY NO 7.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468024_WEST FORK OF CRYSTAL CREEK_g10_1689344234\WEST FORK OF CRYSTAL CREEK.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468026_CRYSTAL CREEK TRIBUTARY NO 2_g10_1689344233\CRYSTAL CREEK TRIBUTARY NO 2.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468026_WF OF CRYSTAL CREEK TRIB NO 1_g10_1689344234\WF OF CRYSTAL CREEK TRIB NO 1.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468026_WF OF CRYSTAL CREEK TRIB NO 2_g10_1689344234\WF OF CRYSTAL CREEK TRIB NO 2.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468052_CRYSTAL CREEK TRIBUTARY NO 1_g10_1689344233\CRYSTAL CREEK TRIBUTARY NO 1.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468062_Crystal Creek 037_g10_1689344233\Crystal Creek 037.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468062_LITTLE CANEY CREEK_g10_1689344233\LITTLE CANEY CREEK.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468062_SILVERDALE CREEK_g10_1689344233\SILVERDALE CREEK.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468064_SANDY BRANCH_g10_1689344233\SANDY BRANCH.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468064_TRADE CTR DITCH_COLLEGE PK DITCH_g10_1689344234\TRADE CTR DITCH_COLLEGE PK DITCH.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468066_HARPERS HORSEPEN BRANCH_g10_1689344233\HARPERS HORSEPEN BRANCH.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468068_CRYSTAL CREEK_g10_1689344233\CRYSTAL CREEK.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468076_Crystal Creek 013_g10_1689344233\Crystal Creek 013.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468080_Crystal Creek 010_g10_1689344233\Crystal Creek 010.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468082_WHITE OAK CREEK WEST TRIB NO 1_g10_1689344234\WHITE OAK CREEK WEST TRIB NO 1.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468086_WHITE OAK CREEK WEST_g10_1689344234\WHITE OAK CREEK WEST.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468092_Crystal Creek 053_g10_1689344233\Crystal Creek 053.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468094_Crystal Creek 009_g10_1689344233\Crystal Creek 009.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468094_WOODSONS GULLY_g10_1689344234\WOODSONS GULLY.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468098_Crystal Creek 008_g10_1689344233\Crystal Creek 008.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468100_Crystal Creek 012_g10_1689344233\Crystal Creek 012.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468100_UNNAMED TRIB TO WOODSONS GULLY_g10_1689344234\UNNAMED TRIB TO WOODSONS GULLY.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468102_Crystal Creek 054_g10_1689344233\Crystal Creek 054.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468104_Crystal Creek 003_g10_1689344233\Crystal Creek 003.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468106_Crystal Creek 002_g10_1689344233\Crystal Creek 002.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468106_Crystal Creek 056_g10_1689344233\Crystal Creek 056.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468258_Crystal Creek 040_g10_1689344233\Crystal Creek 040.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468258_GRAND LAKE CREEK_g10_1689344233\GRAND LAKE CREEK.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468258_STEWARTS CREEK_g10_1689344234\STEWARTS CREEK.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468264_POSSUM BRANCH_g10_1689344233\POSSUM BRANCH.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468266_Crystal Creek 050_g10_1689344233\Crystal Creek 050.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468276_Crystal Creek 039_g10_1689344233\Crystal Creek 039.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1468298_Crystal Creek 006_g10_1689344233\Crystal Creek 006.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1469612_WFSJ Main_g02_1689344234\WFSJ Main.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1469612_WFSJ Main_g02_1689344235\WFSJ Main.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1469612_WFSJ Main_g02_1689344237\WFSJ Main.prj
Empty geometry in C:\ras2fim_data\OWP_ras_models\models_12040101_full\1469612_WFSJ Main_g02_1689344238\WFSJ Main.prj

**Comment by JamesColl-NOAA** [comment]
This particular error is now addressed in the newest version of RRASSLER and the staged OWP model catalog.  I don't know that I'd expect these ones to run given filtering and limitations of RAS2FIM V2 further down the processing chain but that's known/expected.
