### ISSUE TITLE
[8pts] Updates in reformat_ras_rating_curves.py

### ISSUE THREAD

**Issue by EmilyDeardorff** [NOAA-OWP/ras2fim#138]
Here are a few pending update that may/may not be updated to reformat_ras_rating_curves.py

1) Currently, the `source` column in the `reformat_ras_rating_curves.py` outputs is hard-coded as "ras2fim". It would be good to add the ras2fim version to the `source` column (i.e. "ras2fim_1.17.0"). Confirm with Ryan if he needs just the value of "ras2fim" which could be hardcoded, then maybe a second column (source version??) for ras2fim version (which we can auto fill like we did in ras2catchments.  Ryan's part might need logic based exactly based on source column value of "ras2fim".  How does this related to locatoin_type column. So maybe we already have this covered.

2) ~~Change this tool to be split to two separate files~~. ~~One for reformat... that works on a HUC/CRS output folder and can be run as part of ras2fim.py.   The other is the compilation of each set of reformatted rating curves from each hec/crs output folder. into a separate file that can be run as part of ras2release~~. 

3) ~~Add the "compiled_rating_curves" folder if it does not already exist, but validate the rest of the path.  We need to decide if we auto overwrite (aka.. delete the dir and mkdir "compiled_rating_curvers") or stop when it exists, or what. Most of our code, auto deletes if it is there and replaces it. It does not attempt to simply add files in case the folder is ready dirty. PS.. if we need to change this for hucs.. we do need to ensure it is in the path of "huc/crs" output folder / "final" / "compile_rating_curves" so we can merge the values in those folder for each huc/crs output folder into one ras2release version~~.

4) ~~remove wrds_timestamp column. Does Ryan want others added, maybe from OWP_ras_models_catalog_{HUC}_{CRS}.csv~~?

**Comment by RobHanna-NOAA** [comment]
Parts 2, 3 and 4 are now either done or are invalid. Keeping just the first part.

**Comment by CarsonPruitt-NOAA** [comment]
Update the output names per #181

**Comment by RyanSpies-NOAA** [comment]
This [feature branch](https://github.com/NOAA-OWP/inundation-mapping/tree/dev-fix-rascalb-input) has two small changes:
1) ignore the `wrds_timestamp` column from the `reformat_ras_rating_curve_points_rel_101.gpkg` file read
2) updated the ras2fim filepaths to use the `rel_101`

Confirmed that these changes were successfull in running two of the ras2fim hucs (12030106 and 12030105)
