### ISSUE TITLE
[5pt] DEM download error handling

### ISSUE THREAD

**Issue by JamesColl-NOAA** [NOAA-OWP/ras2fim#14]
The DEM downloaded from 3DEP will occasionally fail, adding a check to ensure something was returned dramatically reduced failed runs over Iowa data.

## Example of failed URL:
https://elevation.nationalmap.gov/arcgis/services/3DEPElevation/ImageServer/WCSServer?SERVICE=WCS&VERSION=1.0.0&REQUEST=GetCoverage&coverage=DEP3Elevation&CRS=EPSG:3857&FORMAT=GeoTiff&BBOX=-10291836.0,5163319.0,-10290336.0,5164819.0&WIDTH=500.0&HEIGHT=500.0
![git_url_error](https://user-images.githubusercontent.com/89595253/152778385-94d5f59b-808c-4e7a-9108-35c38fccc8fb.PNG)

## Enhancement
There are two improvements I'm looking for here, one to attempt to retry the failed tiles, and the other to more explicitly report and alert the end user.  This is something that should work but does not, so halting processing, reassessing the issue, and rerunning the model is the appropriate step.  To that end code needs to

1. Check that something was returned, and if not attempt a few more times.
2. explicitly print out paths and halt processing.

**Comment by BradfordBates-NOAA** [comment]
@JamesColl-NOAA Please add points to this issue.
