### ISSUE TITLE
[3pt]  Change ras2fim pre-processing (r / RASSLER) code to UTC date times.

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#153]
Change all date time code in the pre-processing code ("r" and RASSLER) to be UTC time instead of local time.

Note: A different card is being issued for the ras2fim processing side.

**Comment by JamesColl-NOAA** [comment]
This should be the case.  _as.POSIXct_, and therefore the naming convention, is represented in UTC as epoch.
