### ISSUE TITLE
[8pt] Add "get latest" feature to get models by catalog tool.

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#172]
Not yet, but shortly, we expect to start seeing newer version of a model be uploaded to the S3 models folder. Each folder has a Time zero based time stamp (not sure the phrase, but a pure long time number since something like Jan 1, 1970 (??).  ie) 1_ALUM 006_g01_1525461390  (model folder name).. the value of "1525461390" is a long time stamp. This value also shows up in the models catalog.csv in the "last_modified" column.

The need: An optional flag that if True means that if there are two folders with the same starting folder name in S3, not counting the time, then use the newest one only.  e.g.
1_ALUM 006_g01_1525461390  and  1_ALUM 006_g01_1525999999, then 1525999999 is a newer version, so download it only.  But the flag needs to be optional as we do think there might be a time where we might want both down (not sure but keeping the door open).

Priority is lower as we do not yet have newer versions of models being uploaded, but it is not far off.

Note: This may  no longer be needed. RRASSLER is now ensuring the OWP_ras_models_catalog.csv has chagned the status of older ones, so newer models will have the status of "ready". Need to test this a little more.

**Comment by JamesColl-NOAA** [comment]
I don't believe this is necessary any longer as RRASSLER's [_append_catalog_fields_](https://noaa-owp.github.io/RRASSLER/reference/append_catalog_fields.html) accounts for these sorts of updates.
