### ISSUE TITLE
[13pt] ras2fim step1: ras streams exclusion

### ISSUE THREAD

**Issue by hhs732** [NOAA-OWP/ras2fim#219]
Not all RAS streams were added to the outcome of step 1 of ras2fim V1. This needs to be debugged. For example stream RABBS 0352 is not included in `stream_LN_from_ras`, however, its cross sections are in `cross_section_LN_from_ras` file. 

![Image](https://github.com/NOAA-OWP/ras2fim/assets/23247850/03ffb157-409f-4f86-9f6d-7f622841a380)

**Comment by AliForghani-NOAA** [comment]
In ras2fim Step 1 (`create_shapes_from_hecras.py` file) below processes are applied for each RAS model geometry file:

1. If there is no geom HDF file, HEC-RAS is run using geom text file to create a geom HDF file
2. The geom HDF file is processed to read stream coordinates and make a GeoDataFrame for stream centerline.
3. To improve the conflation accuracy in Step 2, the streamline is cut by shortening the portion of the stream that is downstream of the most downstream cross section (using the function `fn_cut_stream_downstream()`). To do this:
                  3-1- The full stream is cut on the most downstream cross section (uses `shapely.ops.split(stream, ds_xsection`). 
                  3-2- The entire river upstream should be merged with only the first segment of the stream downstream.  

However, there is a sneaky bug in section 3-1. The code assumes the result of `shapely.ops.split(stream, ds_xsection)` is a collection of geometries in which the first item is always upstream segment and the second item is downstream segment. This assumption is valid only if the stream coordinates LineString, which are compiled in section 2, are from upstream to downstream. This is not the case for the model `5791442_RABBS 0352` in which **the stream LineString is from downstream to upstream**. Therefore, the final 'shortened' streamline (shown with thicker pink color) erroneously consists of the downstream river merged with the first (and very small) segment of the upstream river.

![image](https://github.com/NOAA-OWP/ras2fim/assets/124194814/b784607b-0436-4550-b60f-124f0406a7eb)

This bug can potentially happen for many other RAS models and needs to be fixed ASAP. Addressing this bug through Section 2, where the stream coordinates LineString must always be compiled from upstream to downstream, might pose increased complexity. Instead, I recommend tackling this bug by revising Section 3-1, focusing on improving the robustness of identifying upstream and downstream segments (not simply by the index of the returned items in `shapely.ops.split(stream, ds_xsection)`).
