### ISSUE TITLE
[8pt] Develop requirements and sample data of reformatted ras2fim rating curves to FIM calibration curve format

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/ras2fim#25]
We want to use the ras2fim rating curves in our HAND FIM calibration scheme. Let's create new versions of the ras2fim feature_id based rating curves that can be easily plugged into the existing HAND FIM rating curve calibration tools.

(@RyanSpies-NOAA @CarsonPruitt-NOAA please fill out the requirements, sharing a template of the final data would be helpful)

Requirements:
- [x] Join lat/lon intersection with ras2fim cross-section ID (a file like this already exists from running ras2fim)
- [x] Reformat rating curves to match column headers expected by calibration tools
- [x] Need the datum for each rating curve
- [ ] ~~Feature ID~~ (will likely need to derive this as part of the lat/lon to hydroid crosswalk process inside fim_run workflow)
- [ ] What else?

**Comment by RyanSpies-NOAA** [comment]
Here is a snippet showing the data format that we use for ingesting USGS gage rating curve data: 
![image](https://user-images.githubusercontent.com/69868854/167692137-ff5e63f6-9660-4125-bebf-6f7a6d3c8034.png)

**Comment by JamesColl-NOAA** [comment]
Data has finally been extracted and merged (yay parquet!).  I have this database in two forms for us, one with metric and the other in freedom units.  As a reminder of this zombie task:
ras2fim produces a rating curve for each NWM reach in a BLE model.  Those NWM streamlines which have a rating curve were collapsed into their terminal point, the terrain elevation was extracted, reprojected to EPSG:6349 (navd88), and merged into a single table using the above field order.
![image](https://user-images.githubusercontent.com/89595253/177343055-3cdb2f87-eef1-4a9b-a014-70c67f9f4adc.png)

**Comment by RyanSpies-NOAA** [comment]
@JamesColl-NOAA awesome - this will be a fun dataset to play with. Do you happen to have the lat/lon locations for those "terminal points"? We probably won't need those points for the calibration workflow, but thought I would check in case we find a use for them.

**Comment by JamesColl-NOAA** [comment]
Updates:
* @RyanSpies-NOAA, yes they are.  per tag up, the merged lat-long-huc8 file has been added to that same folder.  Those files now include:
  * _nwm_line_datums.parquet_: a frame of lat,long,feature_id,and huc8 reprojected to ESRI:102039
  * _nwm_line_datums.csv_: a csv of the above file
  * _hecras_point_geometry.parquet_: point-based frame of geometry _we_ create in running ras2fim
  * _IFC_master_point_dbase.parquet_: point-based frame of all parsable geometry delivered from IFC
  * _rating_curve_calibration_data_*units.parquet_: rating curves per feature_id in * units as described above
* Additional exploration shows that flow (originally in cms) was rounded to an int in processing (sample rating curve in image below), which results in multiple stages for the same apparent flow, and should only occur at low/small flows and places where small changes in discharge result in large changes in stage.
![image](https://user-images.githubusercontent.com/89595253/177364931-0131b629-456a-4a47-a3bd-cb10de2c489f.png)

**Comment by RyanSpies-NOAA** [comment]
Got it. Thanks @JamesColl-NOAA. Also dropping Carson's jam board image here as a reminder to my future self. 
![image](https://user-images.githubusercontent.com/69868854/177575579-e21149af-0695-4389-a518-aa60959d3b6f.png)

**Comment by BradfordBates-NOAA** [comment]
@JamesColl-NOAA @LauraKeys-NOAA @EmilyDeardorff @RyanSpies-NOAA Please schedule time to discuss hand-off of this task to Emily

**Comment by JamesColl-NOAA** [comment]
Looks like you're 
```r
dat <- arrow::read_parquet("B:/inland_routing/data/GID_ras_models/Iowa_Flood_Center_processed/nwm_line_datums.parquet")
dat1 <- arrow::read_parquet("B:/inland_routing/data/GID_ras_models/Iowa_Flood_Center_processed/rating_curve_calibration_data_metricunits.parquet")
calib <- merge(dat, dat1, by.y='location_id', by.x='feature_id')
head(calib)
```
![image](https://user-images.githubusercontent.com/89595253/236548422-2b8146e5-4c6c-40ad-b6d1-606bddace38e.png)

Rating Curve Information: (matched above in logs)
To translate:
- [x] Transform to geopackage (Iowa_Flood_Center_processed/ras2fim_caldb.gpkg)
- [x] location_id (end point of NWM stream line[COMID] -> renamed feature_id)
- [x] huc8 
- [x] point geo in EPSG:5070
- [x] CFS / imperial units
- [x] creating new branch for ras2reformat

**Comment by BradfordBates-NOAA** [comment]
Has this been delivered to Ryan?

**Comment by RyanSpies-NOAA** [comment]
Can we add latitude and longitude attributes to the gpkg?
