### ISSUE TITLE
[2pt] Existence of two qc files for conflation (Step2) results

### ISSUE THREAD

**Issue by AliForghani-NOAA** [NOAA-OWP/ras2fim#270]
The script `src/create_model_domain_polygons.py` needs to read a qc file created as the result of conflation (Step 2). Currently, there are two qc files (`conflated_ras_models.csv` and `12090301_stream_qc_fid_xs.csv`). This can make confusion. Is it possible to remove `conflated_ras_models.csv` since its info can be derived from the other qc file (as unique items of 'ras_path' field). If yes,  make sure to include all fields of `conflated_ras_models.csv` file into the `12090301_stream_qc_fid_xs.csv` file.

**Comment by RobHanna-NOAA** [comment]
The title is incorrect. Any guesses how much work it takes to fix it? We can always adjust it as we get into the actual fix.

**Comment by hhs732** [comment]
Hi Ali and Rob,

This is so much wok, as conflated_ras_models.csv is the input file of
multiple steps. I suggest that we keep both for now and if we had time I’ll
come back to it later.

Thank you,

Heidi

**Comment by hhs732** [comment]
Hi Rob,

I don’t think it is wrong. Step 2 has 2 csv files: one with conflated ras
model path and one with much more information.

Ali, for now let’s keep both, if we have time, I’ll come back to it.

Thank you,
Heidi

**Comment by AliForghani-NOAA** [comment]
Thanks Heidi. ok, that's fine. I close this issue for now.
