### ISSUE TITLE
[3pt] Add feature to create_domain_models to add one big dissolved model poly (full extent)

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#275]
GVAL needs one big poly for all models in a given unit. Aka.. dissolved all of the poly's in the domain_models.gkpg but only for ones that are conflated.

**Comment by AliForghani-NOAA** [comment]
so, maybe I can add some codes to the existing "create_model_domain_polygons.py" to generate this new gpkg file in addition to its current output?

**Comment by RobHanna-NOAA** [comment]
Yup.. that is what I was thinking too. You can do it inside the current create_model... to create. Kinda like a secondary step.
