### ISSUE TITLE
[5pt] Gaps in inundation with latest ras2inundation.py

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/ras2fim#280]
Short description explaining the high-level reason for the new issue.

## Current behavior
There appears to be a bug in the latest version (`dev`) of ras2inundation.py that results in missing inundation extents for some areas. We are testing the code against newly produced geocurve data from the USGS libraries. When running the original RAS2FIM script (the one that draws from precomputed geopackages via the `filename` field, there are no gaps. This is the version of ras2inundation.py that we are running. It has some minor changes, but the core logic is the same as the historically used version (it pulls from precomputed polygons via the `filename` field.

Ideally, the geometry column only could be used, as is designed in the `dev` version of the script, so hopefully this is a simple fix. It could also have to do with bad geometries, however we have confirmed that the geometries are using "is_valid". 

## Expected behavior
Inundation maps with no gaps.

## Steps to replicate behavior (include URLs)
I would try testing to see if this behavior occurs on OWP's existing geocurve data to see if the issue can be reproduced.

## Screenshots
The brown "out_new" (brown) represents the inundation map generated from the `dev` version of ras2inundation.py and the "ras_out" (gray) represents the historical approach where precomputed geopackages are referenced.

<img width="1647" alt="image" src="https://github.com/NOAA-OWP/ras2fim/assets/69594899/07db259b-dbec-405f-a271-e26a16aa3244">

**Comment by RobHanna-NOAA** [comment]
Carson and I researched this and we believe it has been fixed. We back filled the fixed it into the V1 branch but is also in the new dev (v2) branch.  V2 version fix was added in [PR 231](https://github.com/NOAA-OWP/ras2fim/pull/231) and V1 version fix was added as part of [PR 230](https://github.com/NOAA-OWP/ras2fim/pull/230).   Any chance you were working with an older version of ras2inundation.py?  Let me know as I am currently making some minor tweaks to it (now in the tools folder) to give it  more re-ability and traceability.
