### ISSUE TITLE
[5pt] hecras looks for g02

### ISSUE THREAD

**Issue by hhs732** [NOAA-OWP/ras2fim#308]
![Image](https://github.com/NOAA-OWP/ras2fim/assets/23247850/b978becf-fc22-494e-8839-3748055a1eb5)

**Comment by hhs732** [comment]
![Image](https://github.com/NOAA-OWP/ras2fim/assets/23247850/4986773e-126d-47c3-92bd-fa5a5da419fc)

**Comment by RobHanna-NOAA** [comment]
Adding a feature that when loading the list of file in each model, it looks for any files that has a file extension of ['g02', 'g03', 'g04', 'f02', 'f03', 'f04', 'p02', 'p03', 'p04'] and removes those file. Further, I look for lines in when we load the .prj file and remove  those same lines if the line ends with those same values. Test suggest that it is the problem. Multiple files and lines in the prj file that are not "01" files.
