### ISSUE TITLE
[18pt] Ras2fim geocurves black list

### ISSUE THREAD

**Issue by hhs732** [NOAA-OWP/ras2fim#326]
I am looking for geocurves that covers more than one feature-ids. This usually happens where a dam/lake exists downstream a FID. 

![Image](https://github.com/NOAA-OWP/ras2fim/assets/23247850/f8e4fe89-1aa1-426e-aab7-bc01e216e61e)

**Comment by hhs732** [comment]
List completed, there is one HUC, 12010005, that needs to be discussed before handing to hydrovis. 

https://docs.google.com/spreadsheets/d/1Aq-vlmC6Iqndi0GUhPODMfk_WXJusOjHT6WMwftjvHs/edit?pli=1#gid=0

**Comment by CarsonPruitt-NOAA** [comment]
These HUCs were used as part of the ras2fim v2 release and are associated with PR #320
