### ISSUE TITLE
[8pt] Export ras2fim catchment boundary

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/ras2fim#38]
In order to create a reference layer for HydroVIS to identify where we have ras2rems, we need to export a geopackage that contains the full extent of each HUCs ras2rem. This should be added as an enhancement to the catchment raster creation.

**Comment by LauraKeys-NOAA** [comment]
This task has been completed. I need to push these catchment-related updates to the ras2fim repo.

**Comment by BradfordBates-NOAA** [comment]
@CoreyKrewson-NOAA noted that there could be a data type issue @JamesColl-NOAA @LauraKeys-NOAA
