### ISSUE TITLE
[13pt] ras2fim might be pulling external DEMs and should be local only

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#40]
Research required:  get_usgs_dem_from_shape.py is calling a USGS URL and might not using local ones. It needs to changed so it never needs external calls to be run.  Check other code for `urlretrieve`

Also have the inputs have FIM HUC8 DEMs both metric and feet. Check with team if we want the meter version.

-----------------------
Update. Add default to auto load correct ras2fim DEM for the incoming HUC, but only from local inputs, not from S3, all overrideable as usual of course.  Remember.. the more defaulted stuff means much easier to automate at a batch level (super size) (multiple units a time)

**Comment by AliForghani-NOAA** [comment]
Related to this issue, When using all ~1000 HEC-RAS models, ras2fim failed during step 3 (USGS TERRAIN FROM SHAPEFILE) as shown in below screenshot.
Below is the command used:
python ras2fim.py -w 12090301 -i C:/Users/rdp-user/Desktop/Run_ras2fimExample/Austin/models/AllModels -o C:/Users/rdp-user/Desktop/Run_ras2fimExample/Austin/models/outputAllModels -p EPSG:2277 -n C:/ras2fim_data/inputs/X-National_Datasets -r "C:/Program Files (x86)/HEC/HEC-RAS/6.0" -m False
![image](https://github.com/NOAA-OWP/ras2fim/assets/124194814/e32a8d92-ea27-47d7-bc4b-a6607980ace1)

**Comment by RobHanna-NOAA** [comment]
perfect.. thanks for adding that Ali

**Comment by RobHanna-NOAA** [comment]
Latest:  drop live feed

**Comment by CarsonPruitt-NOAA** [comment]
We're going to drop the live pulling of the 3DEP DEMs

**Comment by RobHanna-NOAA** [comment]
This has now been updated and rolled into [PR 252](https://github.com/NOAA-OWP/ras2fim/issues/252)
