### ISSUE TITLE
[1pt] Investigate failure of ras2fim run for "12090301_Meter_2277"

### ISSUE THREAD

**Issue by AliForghani-NOAA** [NOAA-OWP/ras2fim#47]
ras2fim fails even when using a single model in "12090301_Meter_2277". 

## Current behavior
Related to "12090301_Meter_2277" simulation (in Texas), used a single HEC RAS model (5791800_CLEAR 177_g01_1678771301) but ras2fim dev fails in creating any file in "output\05_hecras_output", and therefore it crashes later. 

## Expected behavior
A successful run including ras2rem outputs. 

## Steps to replicate behavior (include URLs)

Below is the command used:
python ras2fim.py -w 12090301 -i InputPath -o OutputPath -p EPSG:2277 -v False -n NationalDatasetsPath -r "C:/Program Files (x86)/HEC/HEC-RAS/6.0"

**Comment by BradfordBates-NOAA** [comment]
@AliForghani-NOAA Did this fix necessitate a code change?

**Comment by AliForghani-NOAA** [comment]
@BradfordBates-NOAA 
We can update the code to address this issue, although it has lower priority now. I reopened the issue for future fix.

**Comment by BradfordBates-NOAA** [comment]
Can this be closed or will one of the upcoming merges resolve this?

**Comment by BradfordBates-NOAA** [comment]
@AliForghani-NOAA Thanks
