### ISSUE TITLE
[5pt] Replace all instances of COMID with feature_id

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/ras2fim#48]
COMID/comid is used throughout ras2fim code, but it appears we are actually meaning NWM feature_id. Let's change instances of comid to feature_id.

---------------
Update: Nov 28, 2023:
The only place that might be a candidate for changing is the simplify_fim_rasters.py for a variable name: str_current_comid = list_path_parts[-3].  After ras v2 is done, we can revisit this and fix if required.

**Comment by BradfordBates-NOAA** [comment]
@LauraKeys-NOAA Please work this into this sprint. I think it could be accomplished as part of the metadata reporting system feature branch you'll make.

**Comment by BradfordBates-NOAA** [comment]
Actually no, let's make a different branch after merging with Rob's latest features.

**Comment by hhs732** [comment]
Addressed in ras2fim V2
