### ISSUE TITLE
[21pt] Update run_ras2rem.py SRC columns

### ISSUE THREAD

**Issue by LauraKeys-NOAA** [NOAA-OWP/ras2fim#50]
The `run_ras2rem.py` file is the "definitive" ras2rem script. Its `make_rating_curve` function needs to be updated with column data and names that are specified in the `ras2rem.py` file function of the same name, which @LauraKeys-NOAA added in the *dev-catchments-ras* branch to ensure `inundation.py`-compliant file outputs.

**Comment by AliForghani-NOAA** [comment]
Related to this issue, is the status of -v flag of ras2fim. Below is what we see in the dev by using python ras2fim.py -h, which shows the user should enter "meter" or "feet" or leave blank:
![image](https://user-images.githubusercontent.com/124194814/236979245-cdbaa65b-247e-402a-a16f-be414020923d.png)

On the other hand, in [README.md](https://github.com/NOAA-OWP/ras2fim#readme), we see below which shows the user should select True or False:
![image](https://user-images.githubusercontent.com/124194814/236979620-cd8d4fa2-0e3c-4d8d-aebb-0b4623177414.png)

Within the code, we see below, which needs verification.
![image](https://user-images.githubusercontent.com/124194814/236979993-ee0d0ba2-eac7-401f-a8a1-a542091a9ff8.png)
