### ISSUE TITLE
[21pt] Investigate failure of ras2fim on step 3 for "12090301_Meter_2277" with all models

### ISSUE THREAD

**Issue by AliForghani-NOAA** [NOAA-OWP/ras2fim#52]
When using all ~1000 HEC-RAS models, ras2fim failed during step 3 (USGS TERRAIN FROM SHAPEFILE) as shown in below screenshot. 

## Steps to replicate behavior (include URLs)

Below is the command used:
python ras2fim.py -w 12090301 -i C:/Users/rdp-user/Desktop/Run_ras2fimExample/Austin/models/AllModels -o C:/Users/rdp-user/Desktop/Run_ras2fimExample/Austin/models/outputAllModels -p EPSG:2277 -n C:/ras2fim_data/inputs/X-National_Datasets -r "C:/Program Files (x86)/HEC/HEC-RAS/6.0" -m False

## Screenshots
![image](https://github.com/NOAA-OWP/ras2fim/assets/124194814/7d78c566-2498-425b-b4aa-3242094e97cb)

**Comment by RobHanna-NOAA** [comment]
Jim states that USGS's site is unstable. If you use the -t flag and specify the DEM to use, it will use that value and not attempt to call USGS. We already have a seperate issue [#40](https://github.com/NOAA-OWP/ras2fim/issues/40) to have all of the DEM's loaded in the inputs directory and no longer attempt to call USGS.   This card can be cancelled.

**Comment by AliForghani-NOAA** [comment]
Agreed, I just copied the screenshot into #40 and closed this one.
