### ISSUE TITLE
[8pt] Convert English units to metric in rating curve creation

### ISSUE THREAD

**Issue by LauraKeys-NOAA** [NOAA-OWP/ras2fim#62]
The current `ras2fim` workflow outputs rating curves in cms and meters if the input model is in metric and in cfs and feet if the input model is in English units. The REM will subsequently be in the same units as the rating curves. I believe we want all our inputs to come out in metric, since that's what we'll ultimately be supplying to Hydrovis.

The `worker_fim_rasters.py` script's rating curve creation function already has a variable that states whether or not the input model is in metric. If it's not in metric, we should convert the discharge and stage values before they get plotted and written out, and only write out metric units and labels.  

If we don't modify the `ras2fim` script, we'll need to modify the `ras2rem` script (or really any script before the inundation).

**Comment by AliForghani-NOAA** [comment]
As elaborated in issue #63 , ras2fim outputs (including depth grids and rating curves in folder "05_hecras_output") will have the same vertical unit (ft or meter) as the vertical unit of RAS models (Ras2fim will be notified of the RAS model vertical unit by V flag). So, if the RAS models vertical unit is already in feet, ras2fim will provide results in feet. To change results to another unit, like meter, it would make sense to use a separate procedure than ras2fim. This may be by developing a stand-alone simple utility to just convert the rem pixel values (or rating curve results) from ft to meter. 
So no further action is needed for ras2fim or ras2rem.
