### ISSUE TITLE
[5pt] Fix proj.db error

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#71]
We are getting error saying something about proj.db not being found. Some developers get it and some to not. 

I researched this heavily and it appears to be a windows sys pathing issue as rasterio ?? creates it in a directory inside /users/ras2fim_user and the code does not have permission to see it. 

I have notes on this but deprioritized it earlier as it is not blocking us for urgent short term goals.

**Comment by AliForghani-NOAA** [comment]
I have not seen this error yet with the original ras2fim environment. Not sure we need to spend too much time on this.
@EmilyDeardorff I think you have been the last person seeing similar error? If so, can you please write here how you changed the code syntax so the error was removed?

**Comment by RobHanna-NOAA** [comment]
Ya.. its a low priority, but I saw it too, which means someone external might get it too. We need to fix or document it if it happens.
