### ISSUE TITLE
[5pt] Add DEM source to output meta data

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/ras2fim#76]
Add DEM source to output meta data. This can be hardcoded temporarily to be the word "FIM", but will become an optional input arg to ras2fim.py and ras2catchments.py. ras2catchments.py makes the meta data file. This can not be done until the DEM inputs are cleaned up and the USGS auto download is removed.

**Comment by CarsonPruitt-NOAA** [comment]
Irrelevant because we're dropping the live 3DEP pulls.
